### ISSUE TITLE
I believe this project could benefit from the entire stack being a `docker-compose up` command

### ISSUE THREAD

**Issue by dillfrescott** [stablecog/stablecog#15]
This would make things much easier for those looking to self-host this software

**Comment by yekta** [comment]
Hey, currently we don't have a use case for docker compose ourselves and don't have time to set it up. There are a lot of moving pieces to the project so it's not particularly straight forward to set up with docker compose (ours is hosted across 4 different cloud providers). We might consider it in the future.

**Comment by dillfrescott** [comment]
Okay
