### ISSUE TITLE
Accept Nano and Banano payments 🙏🏻

### ISSUE THREAD

**Issue by kopeboy** [stablecog/stablecog#19]
Maybe you prefer Stripe for automatic monthly billing for subscriptions, but given your background I'm surprised we can't Pay-per-use with no-fee currencies like XNO and BAN :)

**Comment by yekta** [comment]
We have quite many things to do in our list. The list is prioritized based on the “the potential sum of value provided to users” per “effort on our part”. Integrating XNO or BAN ranks very, very low on that list as it’s quite problematic to implement to our existing structure, it’s tax nightmare and almost none of our users have never heard of those currencies. To put things in perspective, we don’t even have PayPal as an option still 😄 Far easier to deal with, far more people have asked for it and it has 400+ million monthly active users. So roughly more than 1000X of XNO + BAN.

If you want to make suggestions, Discord is more suitable btw: https://stablecog.com/discord

Our issues are for directly code related things, mostly bugs.
