### ISSUE TITLE
CreateContainerConfigError  on AKS  sc-go secretRefs missing dep 

### ISSUE THREAD

**Issue by Pilgrim-Xzed** [stablecog/stablecog#23]
What are the key value pairs for the sc-go secretRefs to enable smooth deployment on k8s  @yekta

**Comment by yekta** [comment]
Hey, you can ask these sorts of questions in our Discord. This repo isn’t the correct one to open such an issue (regarding sc-go) and our issues are for bugs, feature suggestions etc. 

We may provide some of the env vars, however we won’t be able to provide every detail necessary to deploy. As it would take a quite a bit of time on our end which we don’t have currently. When/if we do, we make those available in example vars for everyone to see.
