### ISSUE TITLE
No Session/User Found

### ISSUE THREAD

**Issue by RickRyan26** [stablecog/stablecog#8]
Hello Team,

I love your repo and have been trying to get it up and running so that I can learn from it and maybe one day attempt to contribue. 

I have been stuck on this bug for awhile tho and it would be great to hear your thoughts on it. I am able to successfully log in through supabase's auth and create a Stripe customer but nothing shows up in the supabase database for my user so these errors are thrown. 

I am using `postgresql://postgres:[YOUR-PASSWORD]@db.onelikfckcjoipjwetxo.supabase.co:5432/postgres` (with [YOUR-PASSWORD] replaced of course) as my PUBLIC_SUPABASE_POSTGREST_URL 

![image](https://user-images.githubusercontent.com/72894373/213831503-1f75e4c9-e26b-4934-95b9-9260056e58f2.png)

![image](https://user-images.githubusercontent.com/72894373/213831528-c746389c-857a-4a8a-8142-b0c739143eda.png)

Your thoughts are greatly appreciated and thanks again,
RR

**Comment by yekta** [comment]
Hey, first off, the docs our docs are very outdated. We simply don't have time to update them at the moment. There are a lot of environment variables that aren't in the .env.example. 

Regarding PUBLIC_SUPABASE_POSTGREST_URL, notice how it says "Postgrest" not "Postgres". It should be in this format:
https://{your project id}.supabase.co/rest/v1

**Comment by RickRyan26** [comment]
Thanks Yekta! Well you did an awesome job with the repo, my docs are a bit behind as well.

Updating PUBLIC_SUPABASE_POSTGREST_URL didn't solve the issue :(

For the life of me I can't figure out how to get the user table to show up in Supabase lol

```
PUBLIC_DEFAULT_SERVER_URL
PUBLIC_SUPABASE_URL
PUBLIC_SUPABASE_ANON_KEY
SUPABASE_ADMIN_KEY
PUBLIC_APP_MODE
PUBLIC_CANONICAL_URL
DISCORD_WEBHOOK_URL
R2_ACCESS_KEY_ID
R2_SECRET_ACCESS_KEY
CLOUDFLARE_ACCOUNT_ID
PUBLIC_R2_URL
PUBLIC_SUPABASE_POSTGREST_URL
STRIPE_PRO_PRICE_ID
STRIPE_PRO_PRICE_ID_EUR
STRIPE_SECRET_KEY
STRIPE_SIGNING_SECRET
PUBLIC_MIXPANEL_ID
DISCORD_WEBHOOK_SUBSCRIBER_URL
```

**Comment by yekta** [comment]
User table won’t just show up in Supabase. You need to create the table (and every other table it uses). The schema is also in the repo (although you might not be able to apply it in one go because it also doesn’t track our current schema 1:1).

**Comment by yekta** [comment]
I’ll close the issue for now as this isn’t really an issue/feature request and we aren’t using discussions for now. You can join our Discord and we can talk from there if you have further questions.
